Repository KomodoPlatform/komodo-wallet, pull requests merged in 2020-07, with the labels that each got.

#286 feat(max_taker_vol): add max_taker_vol rpc backend
  src/atomic.dex.mm2.api.cpp
  src/atomic.dex.mm2.api.hpp
Labels: enhancement, next iteration, under testing

#311 improvements(loading_time): try improve loading time
  src/atomic.dex.provider.coinpaprika.cpp
Labels: 0.2.0, Need Testing

#297 feat(candlestick_charts): initial draft candlestick_charts backend
  CMakeLists.txt
  src/atomic.dex.app.cpp
  src/atomic.dex.app.hpp
  src/atomic.dex.provider.cex.prices.api.cpp
  src/atomic.dex.provider.cex.prices.api.hpp
  src/atomic.dex.provider.cex.prices.api.tests.cpp
  src/atomic.dex.provider.cex.prices.cpp
  src/atomic.dex.provider.cex.prices.hpp
  src/atomic.dex.provider.cex.prices.tests.cpp
Labels: 0.2.0, Need Testing, backend, next iteration

#313 feat(addressbook): Starting addressbook feature
  CMakeLists.txt
  src/atomic.dex.app.cpp
  src/atomic.dex.app.hpp
  src/atomic.dex.qt.wallet.manager.hpp
  src/atomic.dex.wallet.config.cpp
  src/atomic.dex.wallet.config.hpp
  src/atomic.dex.wallet.config.tests.cpp
Labels: 0.2.0, backend, under review

#348 Candlestick chart cursor precision and default timescale
  atomic_qt_design/qml/Constants/General.qml
  atomic_qt_design/qml/Exchange/Trade/CandleStickChart.qml
  atomic_qt_design/qml/Exchange/Trade/OrderForm.qml
Labels: under testing

#349 feat(rates): implementation cex_rates in the UI
  atomic_qt_design/qml/Constants/API.qml
  atomic_qt_design/qml/Constants/General.qml
  atomic_qt_design/qml/Exchange/Exchange.qml
  atomic_qt_design/qml/Exchange/Trade/CexInfoTrigger.qml
  atomic_qt_design/qml/Exchange/Trade/ConfirmTradeModal.qml
  atomic_qt_design/qml/Exchange/Trade/OrderForm.qml
  atomic_qt_design/qml/Exchange/Trade/PriceLine.qml
  atomic_qt_design/qml/Exchange/Trade/Trade.qml
  atomic_qt_design/qml/Settings/Settings.qml
  atomic_qt_design/qml/Wallet/Main.qml
  qml.qrc
  src/atomic.dex.app.cpp
  src/atomic.dex.app.hpp
  src/atomic.dex.cfg.cpp
  src/atomic.dex.cfg.hpp
  src/atomic.dex.mm2.api.cpp
  src/atomic.dex.provider.coinpaprika.cpp
  src/atomic.dex.provider.coinpaprika.hpp
  src/atomic.dex.qt.bindings.hpp
Labels: under testing

#393 fix(orders): dissapear / removal
  src/atomic.dex.qt.orders.model.cpp
Labels: under testing
