Repository KomodoPlatform/komodo-wallet, pull requests merged in 2021-12, with the labels that each got.

#1447 Update new Popup Manager
  atomic_defi_design/Dex/App.qml
  atomic_defi_design/Dex/Components/DefaultModal.qml
  atomic_defi_design/Dex/Components/DexDialogTextField.qml
  atomic_defi_design/Dex/Components/PopupManager.qml
  atomic_defi_design/Dex/Dashboard/NewUpdateModal.qml
  atomic_defi_design/Dex/Screens/Startup/WalletsView.qml
  atomic_defi_design/Dex/Settings/SettingModal.qml
  atomic_defi_design/Dex/main.qml
  atomic_defi_design/qml.qrc
Labels: Front-end

#1496 Fix logo with different sizes which might overflow sidebar
  atomic_defi_design/Dex/Sidebar/Main.qml
  atomic_defi_design/Dex/Sidebar/Top.qml
Labels: Front-end

#1517 Change pro trading view settings button style
  atomic_defi_design/Dex/Exchange/Trade/Trading/TradeViewHeader.qml
Labels: 0.5.4

#1515 Change ticker selector hover color in simple trading view
  atomic_defi_design/Dex/Components/ClickableText.qml
  atomic_defi_design/Dex/Components/DexLabel.qml
  atomic_defi_design/Dex/Exchange/Trade/SimpleView/SubCoinSelector.qml
  atomic_defi_design/Dex/Exchange/Trade/SimpleView/Trade.qml
Labels: 0.5.4

#1518 Change outline button style
  atomic_defi_design/Dex/Components/OutlineButton.qml
Labels: 0.5.4

#1519 Make notification popup configurable via themes and change their defa…
  assets/themes/Default - Dark/colors.json
  assets/themes/Default - Light/colors.json
  atomic_defi_design/Dex/App.qml
  atomic_defi_design/Dex/Themes/CurrentTheme.qml
  atomic_defi_design/Dex/Themes/DefaultTheme.js
  atomic_defi_design/Dex/Themes/ThemeData.qml
Labels: 0.5.4

#1523 fix overlapping table header and text
  atomic_defi_design/Dex/Exchange/Trade/SimpleView/SubBestOrder.qml
  atomic_defi_design/Dex/Exchange/Trade/SimpleView/SubCoinSelector.qml
Labels: P0, 0.5.4

#1521 Update pro trading view: trading informations style
  atomic_defi_design/Dex/Components/DexPaginator.qml
  atomic_defi_design/Dex/Components/HorizontalLine.qml
  atomic_defi_design/Dex/Exchange/Trade/Orders/OrderLine.qml
  atomic_defi_design/Dex/Exchange/Trade/Orders/OrderList.qml
  atomic_defi_design/Dex/Exchange/Trade/Orders/OrdersPage.qml
  atomic_defi_design/Dex/Exchange/Trade/PriceLine.qml
  atomic_defi_design/Dex/Exchange/Trade/ProView.qml
Labels: P0, 0.5.4
