Repository KomodoPlatform/komodo-wallet, pull requests merged in 2021-11, with the labels that each got.

#1423 feat(mm2_cfg): network is now optional
  src/core/atomicdex/config/raw.mm2.coins.cfg.hpp
  src/core/atomicdex/services/mm2/mm2.service.cpp
Labels: P0

#1450 feat(password_policy): start transition to new password policy
  src/core/atomicdex/utilities/security.utilities.cpp
  src/core/atomicdex/utilities/security.utilities.hpp
  src/tests/utilities/global.utilities.tests.cpp
Labels: backend, Need Testing

#1449 add TRYB-PLG20
  assets/config/0.5.3-coins.json
  atomic_defi_design/Dex/Constants/General.qml
  atomic_defi_design/Dex/Constants/Style.qml
  atomic_defi_design/assets/images/coins/nzds.png
  atomic_defi_design/qml.qrc
Labels: Front-end, Coin Addition

#1443 fix login page background and button
  atomic_defi_design/Dex/Components/DexAppPasswordField.qml
  atomic_defi_design/Dex/Components/DexAppTextField.qml
  atomic_defi_design/Dex/Components/TextAreaWithTitle.qml
  atomic_defi_design/Dex/Screens/Startup/Login.qml
  atomic_defi_design/Dex/main.qml
Labels: Front-end
