Repository KomodoPlatform/komodo-wallet, pull requests merged in 2022-09, with the labels that each got.

#1963 Add LightningCash (LNC)
  assets/config/0.5.6-coins.json
  atomic_defi_design/Dex/Constants/Style.qml
  atomic_defi_design/assets/images/coins/lnc.png
Labels: Coin Addition

#1971 Fix min vol fiat value
  atomic_defi_design/Dex/Exchange/ProView/PlaceOrderForm/OrderForm.qml
Labels: P1, impact_ux

#1936 build libwally
  .github/workflows/atomicdex-desktop-ci.yml
  wally/wally.dll
Labels: opSEC, CI
