Repository KomodoPlatform/komodo-wallet, pull requests merged in 2023-06, with the labels that each got.

#2229 remove band oracle code
  atomic_defi_design/Dex/Components/CexInfoModal.qml
  atomic_defi_design/assets/languages/atomic_defi_de.ts
  atomic_defi_design/assets/languages/atomic_defi_en.ts
  atomic_defi_design/assets/languages/atomic_defi_es.ts
  atomic_defi_design/assets/languages/atomic_defi_fr.ts
  atomic_defi_design/assets/languages/atomic_defi_lang_template.ts
  atomic_defi_design/assets/languages/atomic_defi_ru.ts
  atomic_defi_design/assets/languages/atomic_defi_tr.ts
  atomic_defi_design/assets/languages/translations_matrix.csv
  src/app/app.cpp
  src/core/atomicdex/events/events.hpp
  src/core/atomicdex/pages/qt.portfolio.page.cpp
  src/core/atomicdex/pages/qt.portfolio.page.hpp
  src/core/atomicdex/services/price/global.provider.cpp
  src/core/atomicdex/services/price/oracle/band.provider.cpp
  src/core/atomicdex/services/price/oracle/band.provider.hpp
Labels: 0.5.8

#2278 Use cmake 3.25.0 so CI/CD builds
  ci_tools_atomic_dex/ci_scripts/windows_script.ps1
Labels: 0.5.8

#2277 Remove Band Oracle Code
  atomic_defi_design/Dex/Components/CexInfoModal.qml
  atomic_defi_design/assets/languages/atomic_defi_de.ts
  atomic_defi_design/assets/languages/atomic_defi_en.ts
  atomic_defi_design/assets/languages/atomic_defi_es.ts
  atomic_defi_design/assets/languages/atomic_defi_fr.ts
  atomic_defi_design/assets/languages/atomic_defi_lang_template.ts
  atomic_defi_design/assets/languages/atomic_defi_ru.ts
  atomic_defi_design/assets/languages/atomic_defi_tr.ts
  atomic_defi_design/assets/languages/translations_matrix.csv
  src/app/app.cpp
  src/core/atomicdex/events/events.hpp
  src/core/atomicdex/pages/qt.portfolio.page.cpp
  src/core/atomicdex/pages/qt.portfolio.page.hpp
  src/core/atomicdex/services/price/global.provider.cpp
  src/core/atomicdex/services/price/oracle/band.provider.cpp
  src/core/atomicdex/services/price/oracle/band.provider.hpp
Labels: 0.5.8, awaiting review

#2280 Fix segwit bestorders
  atomic_defi_design/Dex/App.qml
  atomic_defi_design/Dex/Dashboard/NotificationsModal.qml
  atomic_defi_design/Dex/Wallet/Main.qml
  atomic_defi_design/Dex/Wallet/SendModal.qml
  src/core/atomicdex/api/mm2/orderbook.order.contents.cpp
  src/core/atomicdex/config/coins.cfg.cpp
  src/core/atomicdex/config/coins.cfg.hpp
  src/core/atomicdex/constants/dex.constants.hpp
  src/core/atomicdex/models/qt.orderbook.model.cpp
  src/core/atomicdex/models/qt.orderbook.model.hpp
  src/core/atomicdex/pages/qt.wallet.page.cpp
  src/core/atomicdex/pages/qt.wallet.page.hpp
  src/core/atomicdex/pages/widgets/dex/qt.orderbook.cpp
  src/core/atomicdex/services/mm2/mm2.service.cpp
  src/core/atomicdex/services/mm2/mm2.service.hpp
Labels: 0.5.8, awaiting review

#2288 tweak tooltip
  atomic_defi_design/Dex/Exchange/Trade/SimpleView/Trade.qml
  atomic_defi_design/assets/languages/atomic_defi_de.ts
  atomic_defi_design/assets/languages/atomic_defi_en.ts
  atomic_defi_design/assets/languages/atomic_defi_es.ts
  atomic_defi_design/assets/languages/atomic_defi_fr.ts
  atomic_defi_design/assets/languages/atomic_defi_ru.ts
  atomic_defi_design/assets/languages/atomic_defi_tr.ts
  src/core/atomicdex/models/qt.portfolio.model.cpp
  src/core/atomicdex/models/qt.portfolio.model.hpp
Labels: 0.5.8, awaiting review

#2287 Add assets from sidebar
  atomic_defi_design/Dex/Screens/Dashboard.qml
  atomic_defi_design/Dex/Sidebar/Bottom.qml
  atomic_defi_design/Dex/Sidebar/Main.qml
  atomic_defi_design/assets/images/bank-plus.svg
Labels: 0.5.8, awaiting review

#2279 use swap contract addresses from coins config file
  src/core/atomicdex/api/mm2/rpc.electrum.cpp
  src/core/atomicdex/api/mm2/rpc.electrum.hpp
  src/core/atomicdex/api/mm2/rpc.enable.cpp
  src/core/atomicdex/api/mm2/rpc.enable.hpp
  src/core/atomicdex/config/coins.cfg.cpp
  src/core/atomicdex/config/coins.cfg.hpp
  src/core/atomicdex/services/mm2/mm2.service.cpp
Labels: 0.5.8, awaiting review

#2297 update changelog link
  atomic_defi_design/Dex/Support/SupportModal.qml
Labels: 0.5.8, awaiting review

#2298 add DOC and MARTY faucet buttons
  atomic_defi_design/Dex/Constants/General.qml
  atomic_defi_design/Dex/Wallet/Main.qml
  src/app/app.cpp
  src/core/atomicdex/config/coins.cfg.cpp
  src/core/atomicdex/config/coins.cfg.hpp
  src/core/atomicdex/constants/dex.constants.hpp
  src/core/atomicdex/pages/qt.wallet.page.cpp
Labels: P0, 0.5.8, awaiting review
