Repository KomodoPlatform/komodo-wallet, pull requests merged in 2025-08, with the labels that each got.

#2995 fix missing price and change data on coin page, sync with main wallet…
  lib/bloc/coins_bloc/coins_repo.dart
  lib/shared/utils/extensions/legacy_coin_migration_extensions.dart
  lib/shared/widgets/coin_fiat_change.dart
  lib/shared/widgets/coin_fiat_price.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info_fiat.dart
  lib/views/wallet/wallet_page/common/coin_list_item.dart
  lib/views/wallet/wallet_page/common/coin_list_item_desktop.dart
  lib/views/wallet/wallet_page/common/coin_list_item_mobile.dart
Labels: bug

#3043 fix: prevent blank screen after login
  lib/shared/widgets/app_dialog.dart
Labels: codex

#3044 fix(auth): avoid context usage after login dialog closes
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
Labels: codex

#3046 fix: reset NFT image on url change
  lib/views/nfts/common/widgets/nft_image.dart
Labels: codex

#3049 fix(coin-details): display fiat balance for addresses
  lib/bloc/coin_addresses/bloc/coin_addresses_bloc.dart
  lib/bloc/coin_addresses/bloc/coin_addresses_event.dart
  lib/shared/widgets/coin_balance.dart
  lib/shared/widgets/coin_fiat_balance.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
Labels: bug, QA, codex
