Repository KomodoPlatform/komodo-wallet, pull requests merged in 2025-05, with the labels that each got.

#2615 ci(sdk): Create script/action for SDK auto roll
  .github/actions/flutter-deps/action.yml
  .github/scripts/roll_sdk_packages.sh
  .github/workflows/roll-sdk-packages.yml
Labels: CI

#2611 fix(system-health-check): add additional time providers and update URLs of existing providers
  lib/bloc/app_bloc_root.dart
  lib/bloc/system_health/providers/binance_time_provider.dart
  lib/bloc/system_health/providers/http_head_time_provider.dart
  lib/bloc/system_health/providers/http_time_provider.dart
  lib/bloc/system_health/providers/ntp_time_provider.dart
  lib/bloc/system_health/providers/time_provider.dart
  lib/bloc/system_health/providers/time_provider_registry.dart
  lib/bloc/system_health/system_clock_repository.dart
  lib/bloc/system_health/system_health_bloc.dart
  lib/bloc/system_health/system_health_event.dart
  lib/bloc/system_health/system_health_state.dart
  lib/main.dart
  lib/services/initializer/app_bootstrapper.dart
  lib/shared/ui/clock_warning_banner.dart
  lib/views/bridge/bridge_exchange_form.dart
  lib/views/dex/simple/form/maker/maker_form_trade_button.dart
  lib/views/dex/simple/form/taker/taker_form_content.dart
  lib/views/market_maker_bot/add_market_maker_bot_trade_button.dart
  pubspec.lock
  pubspec.yaml
  test_units/main.dart
  test_units/tests/system_health/http_head_time_provider_test.dart
  test_units/tests/system_health/http_time_provider_test.dart
  test_units/tests/system_health/ntp_time_provider_test.dart
  test_units/tests/system_health/system_clock_repository_test.dart
  test_units/tests/system_health/time_provider_registry_test.dart
Labels: bug, QA

#2608 fix(fiat-onramp): banxa onramp flow erroneous failure popup and return to komodo button
  assets/web_pages/checkout_status_redirect.html
  assets/web_pages/fiat_widget.html
  lib/app_config/app_config.dart
  lib/bloc/fiat/banxa_fiat_provider.dart
  lib/bloc/fiat/base_fiat_provider.dart
  lib/bloc/fiat/fiat_onramp_form/fiat_form_bloc.dart
  lib/bloc/fiat/fiat_onramp_form/fiat_form_state.dart
  lib/bloc/fiat/fiat_order_status.dart
  lib/bloc/fiat/fiat_repository.dart
  lib/bloc/fiat/models/fiat_buy_order_error.dart
  lib/bloc/fiat/models/fiat_buy_order_info.dart
  lib/bloc/fiat/models/fiat_price_info.dart
  lib/bloc/fiat/models/i_currency.dart
  lib/bloc/fiat/payment_status_type.dart
  lib/bloc/fiat/ramp/models/ramp_asset_info.dart
  lib/bloc/fiat/ramp/ramp_fiat_provider.dart
  lib/shared/widgets/coin_item/coin_item.dart
  lib/views/fiat/fiat_asset_icon.dart
  lib/views/fiat/fiat_currency_list_tile.dart
  lib/views/fiat/fiat_form.dart
  lib/views/fiat/fiat_inputs.dart
  lib/views/fiat/fiat_payment_methods_grid.dart
  lib/views/fiat/fiat_provider_web_view_settings.dart
  lib/views/fiat/webview_dialog.dart
Labels: bug, QA

#2638 Fix analytics event data
  lib/analytics/analytics_events.dart
Labels: codex

#2665 Log portfolio pnl viewed analytics events
  Fetching
  lib/analytics/analytics_factory.dart
  lib/main.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_confirmation/seed_confirmation.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_show.dart
  lib/views/wallet/coin_details/coin_details_info/charts/animated_portfolio_charts.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
Labels: codex

#2667 Add analytics callbacks for send and swap events
  lib/analytics/events/transaction_events.dart
  lib/views/dex/entity_details/trading_details.dart
  lib/views/dex/simple/confirm/maker_order_confirmation.dart
  lib/views/dex/simple/confirm/taker_order_confirmation.dart
  lib/views/wallet/coin_details/withdraw_form/withdraw_form.dart
Labels: codex

#2669 Add analytics event hooks
  lib/analytics/events.dart
  lib/bloc/app_bloc_root.dart
  lib/bloc/coin_addresses/bloc/coin_addresses_bloc.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
Labels: codex

#2673 Add portfolio and asset analytics events
  lib/analytics/events/portfolio_events.dart
  lib/bloc/app_bloc_root.dart
  lib/bloc/coins_manager/coins_manager_bloc.dart
  lib/bloc/custom_token_import/bloc/custom_token_import_bloc.dart
  lib/views/custom_token_import/custom_token_import_button.dart
  lib/views/wallet/coin_details/coin_details_info/charts/animated_portfolio_charts.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_overview.dart
Labels: codex

#2677 Implement missing analytics events
  lib/analytics/events/security_events.dart
  lib/analytics/events/user_acquisition_events.dart
  lib/analytics/events/user_engagement_events.dart
  lib/main.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_confirmation/seed_confirmation.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_show.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
Labels: codex

#2683 Implement cross-chain analytics events
  lib/analytics/events/cross_chain_events.dart
  lib/bloc/app_bloc_root.dart
  lib/bloc/bridge_form/bridge_bloc.dart
  lib/views/wallet/coin_details/coin_details.dart
Labels: codex

#2685 Refactor analytics triggers to log events directly
  lib/bloc/app_bloc_root.dart
  lib/bloc/bridge_form/bridge_bloc.dart
  lib/bloc/coin_addresses/bloc/coin_addresses_bloc.dart
  lib/bloc/coins_manager/coins_manager_bloc.dart
  lib/bloc/custom_token_import/bloc/custom_token_import_bloc.dart
  lib/views/bridge/bridge_confirmation.dart
  lib/views/dex/entity_details/trading_details.dart
  lib/views/dex/simple/confirm/maker_order_confirmation.dart
  lib/views/dex/simple/confirm/taker_order_confirmation.dart
  lib/views/nfts/nft_page.dart
  lib/views/wallet/coin_details/coin_details.dart
  lib/views/wallet/coin_details/coin_details_info/charts/animated_portfolio_charts.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/coin_details/rewards/kmd_rewards_info.dart
  lib/views/wallet/coin_details/withdraw_form/withdraw_form.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_overview.dart
  lib/views/wallets_manager/widgets/hardware_wallets_manager.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
Labels: codex

#2651 feat: expand analytics events
  Fetching
  assets/translations/en.json
  docs/ANALYTICS.md
  docs/ANALYTICS_EVENT_IMPLEMENTATION_PLAN.md
  lib/analytics/README.md
  lib/analytics/analytics_factory.dart
  lib/analytics/events.dart
  lib/analytics/events/cross_chain_events.dart
  lib/analytics/events/market_bot_events.dart
  lib/analytics/events/misc_events.dart
  lib/analytics/events/nft_events.dart
  lib/analytics/events/portfolio_events.dart
  lib/analytics/events/reward_events.dart
  lib/analytics/events/security_events.dart
  lib/analytics/events/transaction_events.dart
  lib/analytics/events/user_acquisition_events.dart
  lib/analytics/events/user_engagement_events.dart
  lib/analytics/required_analytics_events.csv
  lib/analytics/widgets/analytics_lifecycle_handler.dart
  lib/bloc/analytics/analytics_bloc.dart
  lib/bloc/analytics/analytics_repo.dart
  lib/bloc/app_bloc_root.dart
  lib/bloc/bridge_form/bridge_bloc.dart
  lib/bloc/coin_addresses/bloc/coin_addresses_bloc.dart
  lib/bloc/coins_manager/coins_manager_bloc.dart
  lib/bloc/custom_token_import/bloc/custom_token_import_bloc.dart
  lib/main.dart
  lib/model/settings/analytics_settings.dart
  lib/services/alpha_version_alert_service/alpha_version_alert_service.dart
  lib/services/initializer/app_bootstrapper.dart
  lib/shared/widgets/alpha_version_warning.dart
  lib/shared/widgets/send_analytics_checkbox.dart
  lib/views/bridge/bridge_confirmation.dart
  lib/views/custom_token_import/custom_token_import_button.dart
  lib/views/dex/entity_details/trading_details.dart
  lib/views/dex/simple/confirm/maker_order_confirmation.dart
  lib/views/dex/simple/confirm/taker_order_confirmation.dart
  lib/views/nfts/nft_page.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_confirmation/seed_confirmation.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_show.dart
  lib/views/wallet/coin_details/coin_details.dart
  lib/views/wallet/coin_details/coin_details_info/charts/animated_portfolio_charts.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/coin_details/rewards/kmd_rewards_info.dart
  lib/views/wallet/coin_details/withdraw_form/withdraw_form.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_overview.dart
  lib/views/wallets_manager/wallets_manager_events_factory.dart
  lib/views/wallets_manager/widgets/hardware_wallets_manager.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
Labels: enhancement, codex

#2655 chore: release notes for v0.9.0
  AGENTS.md
  CHANGELOG.md
  docs/BUILD_RELEASE.md
  docs/BUILD_SECURITY_ADVISORY.md
  docs/RELEASE_NOTES_TEMPLATE.md
Labels: codex

#2620 fix(auth): wallet password validation in creation and update flows
  assets/translations/en.json
  lib/bloc/auth_bloc/auth_bloc.dart
  lib/bloc/settings/settings_bloc.dart
  lib/bloc/settings/settings_event.dart
  lib/bloc/settings/settings_state.dart
  lib/generated/codegen_loader.g.dart
  lib/main.dart
  lib/model/stored_settings.dart
  lib/shared/utils/validators.dart
  lib/views/settings/widgets/general_settings/general_settings.dart
  lib/views/settings/widgets/general_settings/settings_manage_weak_passwords.dart
  lib/views/settings/widgets/security_settings/password_update_page.dart
  lib/views/wallets_manager/widgets/creation_password_fields.dart
  test_units/main.dart
  test_units/tests/password/validate_password_test.dart
Labels: bug, QA
