Repository KomodoPlatform/komodo-wallet, pull requests merged in 2025-07, with the labels that each got.

#2849 feat(wallet): validate deletion form
  lib/views/wallets_manager/widgets/wallet_deleting.dart
Labels: codex

#2854 feat(localization): rename chart key
  assets/translations/en.json
  lib/generated/codegen_loader.g.dart
  lib/views/wallet/wallet_page/common/coins_list_header.dart
Labels: codex

#2857 feat(wallet): add tabs to unauth assets view
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
Labels: codex

#2859 feat(wallet): link asset stats to price chart
  lib/views/wallet/wallet_page/common/asset_list_item.dart
  lib/views/wallet/wallet_page/common/asset_list_item_desktop.dart
  lib/views/wallet/wallet_page/common/assets_list.dart
  lib/views/wallet/wallet_page/common/grouped_asset_ticker_item.dart
  lib/views/wallet/wallet_page/common/grouped_assets_list.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
Labels: codex

#2872 fix: show error on wallet deletion failure
  lib/blocs/wallets_repository.dart
  lib/views/wallets_manager/widgets/wallet_deleting.dart
Labels: codex

#2809 fix: update portfolio growth period change
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_bloc.dart
Labels: codex

#2867 feat(wallet): move add assets action to floating button
  lib/views/fiat/fiat_action_tab.dart
  lib/views/main_layout/main_layout.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
  lib/views/wallet/wallet_page/common/grouped_asset_ticker_item.dart
  lib/views/wallet/wallet_page/wallet_main/balance_summary_widget.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_manage_section.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_overview.dart
  packages/komodo_ui_kit/lib/komodo_ui_kit.dart
  packages/komodo_ui_kit/lib/src/buttons/ui_gradient_button.dart
Labels: codex

#2874 feat(address-creation): use streamed address creation
  lib/bloc/coin_addresses/bloc/coin_addresses_bloc.dart
  lib/bloc/coin_addresses/bloc/coin_addresses_state.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/coin_details/receive/receive_details.dart
  lib/views/wallet/coin_details/receive/trezor_new_address_confirmation.dart
  lib/views/wallet/wallet_page/common/asset_list_item_desktop.dart
  lib/views/wallet/wallet_page/common/grouped_asset_ticker_item.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_overview.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
Labels: codex

#2845 fix(maker-form): use maker max volume instead of balance
  lib/bloc/bridge_form/bridge_bloc.dart
  lib/bloc/bridge_form/bridge_validator.dart
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_event.dart
  lib/bloc/dex_repository.dart
  lib/bloc/taker_form/taker_bloc.dart
  lib/bloc/taker_form/taker_validator.dart
  lib/blocs/maker_form_bloc.dart
  lib/main.dart
  lib/mm2/mm2_api/mm2_api.dart
  lib/mm2/mm2_api/rpc/max_maker_vol/max_maker_vol_response.dart
  lib/shared/utils/utils.dart
  lib/views/dex/dex_helpers.dart
  lib/views/main_layout/main_layout.dart
Labels: bug, QA, codex

#2856 fix(auth): restore logged-in user on app resume
  lib/analytics/widgets/analytics_lifecycle_handler.dart
  lib/bloc/auth_bloc/auth_bloc.dart
  lib/bloc/auth_bloc/auth_bloc_event.dart
  lib/bloc/bridge_form/bridge_bloc.dart
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/dex_tab_bar/dex_tab_bar_bloc.dart
  lib/bloc/nft_transactions/bloc/nft_transactions_bloc.dart
  lib/bloc/nfts/nft_main_bloc.dart
  lib/bloc/taker_form/taker_bloc.dart
  lib/bloc/trezor_connection_bloc/trezor_connection_bloc.dart
  lib/bloc/trezor_init_bloc/trezor_init_bloc.dart
  lib/main.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
Labels: QA

#2853 feat(window): add cross-platform close confirm and shutdown KDF on exit
  .gitignore
  lib/main.dart
  lib/mm2/mm2.dart
  lib/sdk/widgets/window_close_handler.dart
  lib/shared/utils/platform_tuner.dart
  lib/shared/utils/utils.dart
  lib/shared/utils/window/window_native.dart
  lib/views/main_layout/main_layout.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_manage_section.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: bug, enhancement, QA

#2843 feat(wallet): implement wallet deletion
  android/app/build.gradle
  assets/translations/en.json
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/bloc/auth_bloc/auth_bloc.dart
  lib/blocs/wallets_repository.dart
  lib/views/wallets_manager/widgets/wallet_deleting.dart
  lib/views/wallets_manager/widgets/wallet_list_item.dart
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner/Configs/AppInfo.xcconfig
  macos/Runner/Configs/Debug.xcconfig
  macos/Runner/Configs/Release.xcconfig
Labels: QA

#2814 fix: resolve login failure with custom seed and improve withdraw form validation
  .gitignore
  lib/bloc/withdraw_form/withdraw_form_bloc.dart
  lib/views/wallet/coin_details/withdraw_form/withdraw_form.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
  lib/views/wallets_manager/widgets/wallet_creation.dart
  lib/views/wallets_manager/widgets/wallet_simple_import.dart
Labels: bug, QA

#2888 feat(wallet): add order checks on coin disable
  assets/translations/en.json
  lib/blocs/trading_entities_bloc.dart
  lib/generated/codegen_loader.g.dart
  lib/shared/utils/utils.dart
  lib/views/wallet/coins_manager/coins_manager_list_wrapper.dart
Labels: codex

#2890 fix(auth): trezor auth flow and wallet main state updates
  lib/bloc/auth_bloc/auth_bloc.dart
  lib/bloc/auth_bloc/trezor_auth_mixin.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
Labels: bug

#2895 Fix priority mapping for coin sorting
  lib/bloc/coins_bloc/asset_coin_extension.dart
Labels: codex

#2894 chore: bump version to 0.9.2
  pubspec.yaml
Labels: codex

#2898 refactor(feedback): adopt bloc pattern
  lib/bloc/feedback_form/feedback_form_bloc.dart
  lib/bloc/feedback_form/feedback_form_event.dart
  lib/bloc/feedback_form/feedback_form_state.dart
  lib/services/feedback/custom_feedback_form.dart
  lib/services/feedback/feedback_models.dart
Labels: codex

#2901 feat(charts): show updated period immediately
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_bloc.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_state.dart
  lib/bloc/cex_market_data/profit_loss/profit_loss_bloc.dart
  lib/bloc/cex_market_data/profit_loss/profit_loss_state.dart
  lib/views/wallet/coin_details/coin_details_info/charts/portfolio_growth_chart.dart
  lib/views/wallet/coin_details/coin_details_info/charts/portfolio_profit_loss_chart.dart
Labels: codex

#2902 fix: rename statistic card tap handler
  lib/views/wallet/wallet_page/wallet_main/balance_summary_widget.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_overview.dart
  packages/komodo_ui_kit/lib/src/display/statistic_card.dart
Labels: codex

#2907 fix: propagate auth error to login form
  lib/bloc/auth_bloc/auth_bloc_state.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
Labels: codex

#2807 feat(feedback): require contact details for support
  assets/translations/en.json
  lib/bloc/feedback_form/feedback_form_bloc.dart
  lib/bloc/feedback_form/feedback_form_event.dart
  lib/bloc/feedback_form/feedback_form_state.dart
  lib/generated/codegen_loader.g.dart
  lib/services/feedback/custom_feedback_form.dart
  lib/services/feedback/feedback_models.dart
  lib/services/feedback/feedback_service.dart
  lib/shared/constants.dart
Labels: QA, codex

#2912 fix(theme): color switch track
  app_theme/lib/src/dark/theme_global_dark.dart
  app_theme/lib/src/light/theme_global_light.dart
Labels: codex

#2911 refactor: rework feedback encoding
  lib/services/feedback/feedback_models.dart
  lib/services/feedback/feedback_service.dart
  lib/shared/utils/extensions/string_extensions.dart
  packages/komodo_ui_kit/lib/src/controls/market_chart_header_controls.dart
  packages/komodo_ui_kit/lib/src/controls/selected_coin_graph_control.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
Labels: bug

#2913 fix(fiat-onramp): improve fiat provider fault tolerance
  lib/bloc/fiat/fiat_repository.dart
  lib/bloc/fiat/ramp/models/host_assets_config.dart
  lib/bloc/fiat/ramp/ramp_api_utils.dart
  lib/bloc/fiat/ramp/ramp_fiat_provider.dart
Labels: codex

#2921 feat(fiat-onramp): restrict currency input to 2 decimal places
  lib/bloc/fiat/fiat_onramp_form/fiat_form_bloc.dart
  lib/bloc/fiat/fiat_onramp_form/fiat_form_event.dart
  lib/views/fiat/custom_fiat_input_field.dart
  lib/views/fiat/fiat_form.dart
Labels: codex

#2928 feat(wallet): enable asset statistics chart navigation
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
  lib/views/wallet/wallet_page/wallet_main/active_coins_list.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
Labels: codex

#2915 fix(fiat-onramp): improve fiat onramp fault tolerance, error handling, and logging
  lib/app_config/app_config.dart
  lib/bloc/app_bloc_root.dart
  lib/bloc/coins_bloc/asset_coin_extension.dart
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_repo.dart
  lib/bloc/fiat/fiat_onramp_form/fiat_form_bloc.dart
  lib/bloc/fiat/fiat_onramp_form/fiat_form_event.dart
  lib/bloc/fiat/fiat_repository.dart
  lib/bloc/fiat/ramp/models/host_assets_config.dart
  lib/bloc/fiat/ramp/ramp_api_utils.dart
  lib/bloc/fiat/ramp/ramp_fiat_provider.dart
  lib/main.dart
  lib/views/fiat/custom_fiat_input_field.dart
  lib/views/fiat/fiat_form.dart
  lib/views/fiat/fiat_inputs.dart
  lib/views/fiat/fiat_page.dart
Labels: bug, QA

#2930 feat(support): add missing coins option to feedback
  assets/translations/en.json
  docs/LOCALIZATION.md
  lib/bloc/feedback_form/feedback_form_bloc.dart
  lib/generated/codegen_loader.g.dart
  lib/services/feedback/custom_feedback_form.dart
  lib/services/feedback/feedback_models.dart
  lib/views/settings/widgets/support_page/support_item.dart
  lib/views/settings/widgets/support_page/support_page.dart
  lib/views/support/missing_coins_dialog.dart
  lib/views/wallets_manager/wallets_manager_wrapper.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
  lib/views/wallets_manager/widgets/wallet_login.dart
  lib/views/wallets_manager/widgets/wallets_manager.dart
Labels: QA, codex

#2938 fix(withdraw): revert temporary IBC channel field type workaround
  assets/translations/en.json
  lib/bloc/withdraw_form/withdraw_form_bloc.dart
  lib/bloc/withdraw_form/withdraw_form_state.dart
  lib/generated/codegen_loader.g.dart
  lib/views/wallet/coin_details/withdraw_form/widgets/fill_form/fields/fields.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
Labels: bug, QA

#2961 feat: store hide zero balance per wallet
  lib/bloc/settings/settings_bloc.dart
  lib/bloc/settings/settings_repository.dart
  lib/model/kdf_auth_metadata_extension.dart
Labels: codex

#2962 fix(trezor): disable Trezor with a warning on unsupported browsers
  assets/translations/en.json
  lib/analytics/widgets/analytics_lifecycle_handler.dart
  lib/app_config/app_config.dart
  lib/bloc/app_bloc_root.dart
  lib/bloc/platform/platform_bloc.dart
  lib/bloc/platform/platform_event.dart
  lib/bloc/platform/platform_state.dart
  lib/blocs/wallets_repository.dart
  lib/generated/codegen_loader.g.dart
  lib/services/logger/get_logger.dart
  lib/services/logger/universal_logger.dart
  lib/services/platform_info/native_platform_info.dart
  lib/services/platform_info/plaftorm_info.dart
  lib/services/platform_info/platform_info.dart
  lib/services/platform_info/stub.dart
  lib/services/platform_info/web_platform_info.dart
  lib/shared/utils/browser_helpers.dart
  lib/views/common/hw_wallet_dialog/hw_dialog_wallet_select.dart
  lib/views/wallets_manager/widgets/wallet_type_list_item.dart
Labels: bug, QA

#2946 fix(wallet): persist hd status and default to non-hd
  lib/views/wallets_manager/wallets_manager_wrapper.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
  lib/views/wallets_manager/widgets/wallet_creation.dart
  lib/views/wallets_manager/widgets/wallet_import_by_file.dart
  lib/views/wallets_manager/widgets/wallet_login.dart
  lib/views/wallets_manager/widgets/wallet_simple_import.dart
  lib/views/wallets_manager/widgets/wallets_manager.dart
Labels: codex

#2973 feat(activation): show enabled assets in Add Assets page
  lib/bloc/coins_manager/coins_manager_bloc.dart
Labels: codex

#2955 feat(ui): Show full pubkeys where copyable
  lib/shared/utils/formatters.dart
  lib/shared/widgets/copied_text.dart
  lib/views/support/missing_coins_dialog.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/coin_details/transactions/transaction_details.dart
  lib/views/wallet/coin_details/transactions/transaction_list.dart
  lib/views/wallet/coin_details/transactions/transaction_list_item.dart
  lib/views/wallet/common/address_text.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
Labels: P0, QA

#2967 feat(settings): hide log export when logged out
  lib/views/settings/widgets/general_settings/general_settings.dart
Labels: codex

#2968 fix(ui): remove conflicting autofocus and add new focuses
  lib/services/feedback/custom_feedback_form.dart
  lib/shared/ui/borderless_search_field.dart
  lib/views/common/hw_wallet_dialog/trezor_steps/trezor_dialog_select_wallet.dart
  lib/views/common/wallet_password_dialog/password_dialog_content.dart
  lib/views/dex/dex_list_filter/mobile/dex_list_filter_coins_list_mobile.dart
  lib/views/wallet/coin_details/withdraw_form/widgets/fill_form/fields/fields.dart
  lib/views/wallet/coin_details/withdraw_form/widgets/fill_form/fields/fill_form_recipient_address.dart
  lib/views/wallet/coins_manager/coins_manager_controls.dart
  lib/views/wallets_manager/widgets/wallet_deleting.dart
  lib/views/wallets_manager/widgets/wallet_import_by_file.dart
  lib/views/wallets_manager/widgets/wallet_login.dart
Labels: codex

#2981 feat(ci): Implement SDK KDF preview
  .github/workflows/sdk-integration-preview.yml
Labels: CI

#2991 fix(wallets): conditionally show wallet divider
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
Labels: codex

#2990 Show skeleton for assets list addresses
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
Labels: codex

#3005 feat(ui): add hero animations for coin icons
  lib/shared/widgets/asset_item/asset_item.dart
  lib/shared/widgets/coin_item/coin_item.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/coins_manager/coins_manager_list_item.dart
  lib/views/wallet/wallet_page/common/asset_list_item_desktop.dart
  lib/views/wallet/wallet_page/common/asset_list_item_mobile.dart
  lib/views/wallet/wallet_page/common/coin_list_item_desktop.dart
  lib/views/wallet/wallet_page/common/coin_list_item_mobile.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
  lib/views/wallet/wallet_page/common/grouped_asset_ticker_item.dart
Labels: codex

#2992 fix(ui): match fade effect to theme
  lib/shared/ui/fading_edge_scroll_view.dart
Labels: codex

#3018 feat(analytics): add searchbar and theme events
  lib/bloc/coins_manager/coins_manager_bloc.dart
  lib/views/settings/widgets/general_settings/settings_theme_switcher.dart
Labels: codex

#3010 fix(nft): implement parent coin activation for NFTs
  lib/bloc/coins_bloc/coins_repo.dart
  lib/bloc/nfts/nft_main_bloc.dart
  lib/bloc/nfts/nft_main_repo.dart
  lib/mm2/mm2_api/mm2_api_nft.dart
  packages/komodo_ui_kit/lib/src/skeleton_loaders/skeleton_loader_list_tile.dart
Labels: bug, QA, codex

#2982 feat(wallet): HD & offline private key export + unban pubkeys
  assets/translations/en.json
  lib/bloc/security_settings/security_settings_bloc.dart
  lib/bloc/security_settings/security_settings_event.dart
  lib/bloc/security_settings/security_settings_state.dart
  lib/generated/codegen_loader.g.dart
  lib/model/hd_account/hd_account.dart
  lib/views/common/main_menu/main_menu_desktop_item.dart
  lib/views/common/wallet_password_dialog/password_dialog_content.dart
  lib/views/common/wallet_password_dialog/wallet_password_dialog.dart
  lib/views/settings/widgets/general_settings/settings_manage_trading_bot.dart
  lib/views/settings/widgets/security_settings/change_password_section.dart
  lib/views/settings/widgets/security_settings/plate_private_key_backup.dart
  lib/views/settings/widgets/security_settings/plate_seed_backup.dart
  lib/views/settings/widgets/security_settings/private_key_settings/private_key_actions_widget.dart
  lib/views/settings/widgets/security_settings/private_key_settings/private_key_show.dart
  lib/views/settings/widgets/security_settings/security_action_plate.dart
  lib/views/settings/widgets/security_settings/security_settings_main_page.dart
  lib/views/settings/widgets/security_settings/security_settings_page.dart
  lib/views/settings/widgets/security_settings/unban_pubkeys_dialog.dart
  lib/views/settings/widgets/security_settings/unban_pubkeys_plate.dart
  lib/views/settings/widgets/settings_menu/settings_menu_item.dart
  lib/views/wallet/coin_details/coin_details_info/charts/coin_sparkline.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
  lib/views/wallet/wallet_page/common/expandable_private_key_list.dart
  lib/views/wallet/wallet_page/common/grouped_asset_ticker_item.dart
  lib/views/wallet/wallet_page/wallet_main/active_coins_list.dart
  packages/komodo_ui_kit/lib/src/skeleton_loaders/skeleton_loader_list_tile.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
  pubspec.yaml
Labels: QA

#3034 fix(trezor): pin input not visible in light mode
  app_theme/lib/src/light/theme_custom_light.dart
  lib/bloc/auth_bloc/trezor_auth_mixin.dart
  lib/views/common/hw_wallet_dialog/show_trezor_pin_dialog.dart
Labels: bug
