Repository KomodoPlatform/komodo-wallet, pull requests merged in 2025-03, with the labels that each got.

#2556 chore(sdk): Roll KDF SDK to `af79b7d09ab3f3b45ff6767b9556c514f09b25ce`
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
Labels: bug, chore

#2553 fix(auth): backup seed notification banner not appearing for newly created wallets
  lib/bloc/app_bloc_root.dart
  lib/bloc/auth_bloc/auth_bloc.dart
  lib/bloc/auth_bloc/auth_bloc_event.dart
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/nft_receive/bloc/nft_receive_bloc.dart
  lib/bloc/security_settings/security_settings_bloc.dart
  lib/bloc/security_settings/security_settings_state.dart
  lib/bloc/trezor_connection_bloc/trezor_connection_bloc.dart
  lib/blocs/current_wallet_bloc.dart
  lib/blocs/wallets_repository.dart
  lib/main.dart
  lib/model/kdf_auth_metadata_extension.dart
  lib/views/fiat/fiat_form.dart
  lib/views/main_layout/main_layout.dart
  lib/views/nfts/nft_receive/nft_receive_page.dart
  lib/views/settings/widgets/security_settings/password_update_page.dart
  lib/views/settings/widgets/security_settings/plate_seed_backup.dart
  lib/views/settings/widgets/security_settings/security_settings_page.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_confirmation/seed_confirmation.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_show.dart
  lib/views/wallet/coin_details/coin_details_info/charts/portfolio_profit_loss_chart.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
  lib/views/wallets_manager/widgets/wallet_import_wrapper.dart
Labels: bug, QA

#2554 fix(auth): missing login failed error and BIP39 validation clarification
  assets/translations/en.json
  lib/bloc/auth_bloc/auth_bloc.dart
  lib/bloc/auth_bloc/auth_bloc_event.dart
  lib/bloc/auth_bloc/auth_bloc_state.dart
  lib/generated/codegen_loader.g.dart
  lib/views/common/wallet_password_dialog/password_dialog_content.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
  lib/views/wallets_manager/widgets/wallet_login.dart
  lib/views/wallets_manager/widgets/wallet_simple_import.dart
  packages/komodo_ui_kit/lib/src/inputs/ui_text_form_field.dart
Labels: bug

#2550 chore: remove build_config.json
  .github/actions/validate-build/action.yml
  app_build/BUILD_CONFIG_README.md
  app_build/build_config.json
  docs/BUILD_CONFIG.md
  lib/views/settings/widgets/general_settings/app_version_number.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
  pubspec.yaml
Labels: documentation, enhancement

#2558 fix(market-metrics): hd mode switching values shown, graph interaction, and loading speed
  lib/bloc/app_bloc_root.dart
  lib/bloc/assets_overview/bloc/asset_overview_bloc.dart
  lib/bloc/auth_bloc/auth_bloc.dart
  lib/bloc/cex_market_data/mockup/generator.dart
  lib/bloc/cex_market_data/mockup/mock_portfolio_growth_repository.dart
  lib/bloc/cex_market_data/mockup/mock_transaction_history_repository.dart
  lib/bloc/cex_market_data/models/adapters/graph_cache_adapter.dart
  lib/bloc/cex_market_data/models/graph_cache.dart
  lib/bloc/cex_market_data/portfolio_growth/cache_miss_exception.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_bloc.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_repository.dart
  lib/bloc/cex_market_data/profit_loss/demo_profit_loss_repository.dart
  lib/bloc/cex_market_data/profit_loss/models/adapters/profit_loss_adapter.dart
  lib/bloc/cex_market_data/profit_loss/models/adapters/profit_loss_cache_adapter.dart
  lib/bloc/cex_market_data/profit_loss/models/profit_loss_cache.dart
  lib/bloc/cex_market_data/profit_loss/profit_loss_bloc.dart
  lib/bloc/cex_market_data/profit_loss/profit_loss_calculator.dart
  lib/bloc/cex_market_data/profit_loss/profit_loss_repository.dart
  lib/bloc/cex_market_data/sdk_auth_activation_extension.dart
  lib/bloc/coins_bloc/asset_coin_extension.dart
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_repo.dart
  lib/model/kdf_auth_metadata_extension.dart
  lib/model/wallet.dart
  lib/services/logger/get_logger.dart
  lib/shared/utils/utils.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, QA

#2579 feat: Rework unauthenticated assets list
  firebase.json
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_state.dart
  lib/main.dart
  lib/model/cex_price.dart
  lib/shared/utils/extensions/collection_extensions.dart
  lib/shared/utils/utils.dart
  lib/shared/widgets/asset_item/asset_item.dart
  lib/shared/widgets/asset_item/asset_item_body.dart
  lib/shared/widgets/asset_item/asset_item_size.dart
  lib/shared/widgets/asset_item/asset_item_subtitle.dart
  lib/shared/widgets/asset_item/asset_item_title.dart
  lib/views/wallet/coin_details/coin_details_info/charts/coin_sparkline.dart
  lib/views/wallet/wallet_page/common/asset_list_item.dart
  lib/views/wallet/wallet_page/common/asset_list_item_desktop.dart
  lib/views/wallet/wallet_page/common/asset_list_item_mobile.dart
  lib/views/wallet/wallet_page/common/assets_list.dart
  lib/views/wallet/wallet_page/common/coin_list_item_desktop.dart
  lib/views/wallet/wallet_page/common/grouped_asset_ticker_item.dart
  lib/views/wallet/wallet_page/common/grouped_assets_list.dart
  lib/views/wallet/wallet_page/common/wallet_coins_list.dart
  lib/views/wallet/wallet_page/wallet_main/all_coins_list.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
  macos/Podfile.lock
Labels: QA
