Repository KomodoPlatform/komodo-wallet, pull requests merged in 2025-02, with the labels that each got.

#2512 [0.8.3+0] RC: add arbitrum coin type and private key export
  assets/translations/en.json
  lib/app_config/app_config.dart
  lib/bloc/dex_repository.dart
  lib/bloc/fiat/base_fiat_provider.dart
  lib/bloc/taker_form/taker_bloc.dart
  lib/bloc/taker_form/taker_event.dart
  lib/blocs/maker_form_bloc.dart
  lib/generated/codegen_loader.g.dart
  lib/mm2/mm2_api/mm2_api.dart
  lib/mm2/mm2_api/rpc/show_priv_key/show_priv_key_request.dart
  lib/mm2/mm2_api/rpc/show_priv_key/show_priv_key_response.dart
  lib/model/coin.dart
  lib/model/coin_type.dart
  lib/model/coin_utils.dart
  lib/router/navigators/app_router_delegate.dart
  lib/router/parsers/dex_route_parser.dart
  lib/router/parsers/root_route_parser.dart
  lib/router/routes.dart
  lib/router/state/dex_state.dart
  lib/shared/constants.dart
  lib/shared/utils/prominent_colors.dart
  lib/shared/utils/utils.dart
  lib/shared/widgets/coin_item/coin_logo.dart
  lib/shared/widgets/coin_type_tag.dart
  lib/shared/widgets/logout_popup.dart
  lib/views/dex/entities_list/dex_list_wrapper.dart
  lib/views/dex/simple/form/maker/maker_form_layout.dart
  lib/views/dex/simple/form/taker/taker_form.dart
  lib/views/dex/simple/form/taker/taker_form_layout.dart
  lib/views/settings/widgets/general_settings/general_settings.dart
  lib/views/settings/widgets/security_settings/security_settings_page.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_show.dart
  lib/views/wallet/coin_details/transactions/transaction_table.dart
  packages/komodo_ui_kit/lib/src/images/coin_icon.dart
Labels: QA, opSEC pending

#2522 perf(add-coins): improve "Add Assets" coin list loading speed
  lib/bloc/app_bloc_root.dart
  lib/bloc/assets_overview/bloc/asset_overview_bloc.dart
  lib/bloc/assets_overview/investment_repository.dart
  lib/bloc/cex_market_data/mockup/generate_demo_data.dart
  lib/bloc/cex_market_data/mockup/generator.dart
  lib/bloc/cex_market_data/mockup/mock_portfolio_growth_repository.dart
  lib/bloc/cex_market_data/mockup/mock_transaction_history_repository.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_bloc.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_repository.dart
  lib/bloc/cex_market_data/price_chart/price_chart_bloc.dart
  lib/bloc/cex_market_data/profit_loss/demo_profit_loss_repository.dart
  lib/bloc/cex_market_data/profit_loss/profit_loss_bloc.dart
  lib/bloc/cex_market_data/profit_loss/profit_loss_repository.dart
  lib/bloc/coins_bloc/asset_coin_extension.dart
  lib/bloc/coins_bloc/coins_repo.dart
  lib/bloc/coins_manager/coins_manager_bloc.dart
  lib/bloc/coins_manager/coins_manager_event.dart
  lib/bloc/coins_manager/coins_manager_state.dart
  lib/bloc/transaction_history/transaction_history_bloc.dart
  lib/bloc/transaction_history/transaction_history_repo.dart
  lib/model/coin.dart
  lib/views/wallet/coin_details/transactions/transaction_details.dart
  lib/views/wallet/coins_manager/coins_manager_page.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_manage_section.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
  test_units/tests/cex_market_data/generate_demo_data_test.dart
  test_units/tests/utils/test_util.dart
Labels: bug

#2525 fix(transaction-history): incorrect transaction history shown when switching coins
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_repo.dart
  lib/bloc/taker_form/taker_bloc.dart
  lib/bloc/transaction_history/transaction_history_bloc.dart
  lib/bloc/transaction_history/transaction_history_state.dart
  lib/generated/codegen_loader.g.dart
  lib/router/parsers/root_route_parser.dart
Labels: bug

#2527 fix(coins-bloc): coin deactivation not triggering state change and Bloc rebuild
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_repo.dart
Labels: bug

#2515 feat: Custom Token Import UI and BLoC
  assets/logo/not_found.png
  assets/translations/en.json
  lib/bloc/auth_bloc/auth_bloc.dart
  lib/bloc/cex_market_data/mockup/generate_demo_data.dart
  lib/bloc/coins_bloc/asset_coin_extension.dart
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_repo.dart
  lib/bloc/coins_manager/coins_manager_bloc.dart
  lib/bloc/custom_token_import/bloc/custom_token_import_bloc.dart
  lib/bloc/custom_token_import/bloc/custom_token_import_event.dart
  lib/bloc/custom_token_import/bloc/custom_token_import_state.dart
  lib/bloc/custom_token_import/data/custom_token_import_repository.dart
  lib/bloc/fiat/base_fiat_provider.dart
  lib/bloc/nft_withdraw/nft_withdraw_bloc.dart
  lib/bloc/transaction_history/transaction_history_repo.dart
  lib/bloc/trezor_bloc/trezor_repo.dart
  lib/bloc/trezor_init_bloc/trezor_init_bloc.dart
  lib/blocs/current_wallet_bloc.dart
  lib/generated/codegen_loader.g.dart
  lib/mm2/mm2.dart
  lib/mm2/mm2_api/mm2_api.dart
  lib/mm2/mm2_api/rpc/convert_address/convert_address_request.dart
  lib/mm2/mm2_api/rpc/max_maker_vol/max_maker_vol_response.dart
  lib/model/cex_price.dart
  lib/model/coin.dart
  lib/model/hd_account/hd_account.dart
  lib/model/kdf_auth_metadata_extension.dart
  lib/model/wallet.dart
  lib/views/custom_token_import/custom_token_import_button.dart
  lib/views/custom_token_import/custom_token_import_dialog.dart
  lib/views/fiat/fiat_currency_list_tile.dart
  lib/views/nfts/details_page/nft_details_page.dart
  lib/views/wallet/coins_manager/coins_manager_controls.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
  lib/views/wallet/wallet_page/wallet_page.dart
  packages/komodo_ui_kit/lib/src/images/coin_icon.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
  test_units/tests/utils/test_util.dart
Labels: enhancement, new feature

#2529 chore(flutter): Upgrade to Flutter 3.29 and Lock Dependencies for Release
  analysis_options.yaml
  android/app/build.gradle
  app_theme/lib/src/dark/theme_global_dark.dart
  app_theme/lib/src/light/theme_global_light.dart
  app_theme/pubspec.lock
  app_theme/pubspec.yaml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/bloc/analytics/analytics_repo.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/coin_details/receive/qr_code_address.dart
  macos/.gitignore
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/komodo_cex_market_data/pubspec.lock
  packages/komodo_cex_market_data/pubspec.yaml
  packages/komodo_persistence_layer/pubspec.yaml
  packages/komodo_ui_kit/pubspec.lock
  packages/komodo_ui_kit/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#2530 feat(hd): HD withdrawals and portfolio overview
  assets/translations/en.json
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_event.dart
  lib/bloc/coins_bloc/coins_state.dart
  lib/bloc/withdraw_form/withdraw_form_bloc.dart
  lib/bloc/withdraw_form/withdraw_form_state.dart
  lib/generated/codegen_loader.g.dart
  lib/shared/widgets/coin_balance.dart
  lib/views/dex/simple/form/tables/coins_table/coins_table_item.dart
  lib/views/wallet/coin_details/coin_details_info/charts/animated_portfolio_charts.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/coin_details/transactions/transaction_details.dart
  lib/views/wallet/coin_details/withdraw_form/widgets/fill_form/fields/custom_fee/fill_form_custom_fee.dart
  lib/views/wallet/coin_details/withdraw_form/withdraw_form.dart
  lib/views/wallet/wallet_page/common/coin_list_item.dart
  lib/views/wallet/wallet_page/common/coin_list_item_desktop.dart
  lib/views/wallet/wallet_page/common/coins_list_header.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
  lib/views/wallet/wallet_page/wallet_main/active_coins_list.dart
  lib/views/wallet/wallet_page/wallet_main/all_coins_list.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_manage_section.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_manager_search_field.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_overview.dart
  packages/komodo_ui_kit/lib/src/tips/ui_spinner.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
Labels: enhancement, new feature

#2531 ci: upgrade workflows to flutter 3.29
  .devcontainer/komodo-wallet-android-dev.dockerfile
  .docker/komodo-wallet-android.dockerfile
  .github/actions/flutter-deps/action.yml
  android/app/build.gradle
  docs/FLUTTER_VERSION.md
  pubspec.yaml
Labels: bug, CI

#2545 fix: missing segwit badges
  lib/bloc/coins_bloc/asset_coin_extension.dart
  lib/bloc/coins_bloc/coins_repo.dart
  packages/komodo_ui_kit/lib/src/inputs/ui_text_form_field.dart
Labels: bug

#2542 build: fix Docker and Dev Container Flutter 3.29 build error
  .devcontainer/Dockerfile
  .devcontainer/dev-setup.sh
  .devcontainer/devcontainer.json
  .devcontainer/komodo-wallet-android-dev.dockerfile
  .docker/android-sdk.dockerfile
  .docker/build.sh
  .docker/kdf-android.dockerfile
  .docker/komodo-wallet-android.dockerfile
  .dockerignore
Labels: bug

#2534 docs: update the project and flutter setup docs
  docs/BUILD_RUN_APP.md
  docs/FIREBASE_SETUP.md
  docs/FLUTTER_VERSION.md
  docs/INSTALL_FLUTTER.md
  docs/MULTIPLE_FLUTTER_VERSIONS.md
  docs/PROJECT_SETUP.md
Labels: documentation

#2549 bug(auth): Remove `bip39` dependency and fix registration flow on Windows
  lib/model/wallet.dart
  lib/shared/utils/utils.dart
  lib/views/settings/widgets/security_settings/seed_settings/seed_show.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallets_manager/widgets/iguana_wallets_manager.dart
  lib/views/wallets_manager/widgets/wallet_creation.dart
  lib/views/wallets_manager/widgets/wallet_import_by_file.dart
  lib/views/wallets_manager/widgets/wallet_simple_import.dart
  pubspec.lock
  pubspec.yaml
  test_integration/helpers/restore_wallet.dart
Labels: bug, enhancement
