Repository KomodoPlatform/komodo-wallet, pull requests merged in 2025-06, with the labels that each got.

#2734 Update docs for VS Code and web port usage
  docs/BUILD_RUN_APP.md
  docs/MANUAL_TESTING_DEBUGGING.md
  docs/PROJECT_SETUP.md
Labels: codex

#2682 fix: add IBC channel option for withdrawals
  assets/translations/en.json
  lib/bloc/withdraw_form/withdraw_form_bloc.dart
  lib/bloc/withdraw_form/withdraw_form_state.dart
  lib/generated/codegen_loader.g.dart
  lib/views/wallet/coin_details/withdraw_form/widgets/fill_form/fields/fields.dart
  lib/views/wallet/coin_details/withdraw_form/withdraw_form.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
Labels: bug, QA, codex

#2743 chore(release): `v0.9.1` release - Trezor login hot-fix
  CHANGELOG.md
  docs/FLUTTER_VERSION.md
  lib/bloc/app_bloc_root.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_bloc.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_repository.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_state.dart
  lib/bloc/cex_market_data/price_chart/models/price_chart_interval.dart
  lib/bloc/cex_market_data/price_chart/models/time_period.dart
  lib/bloc/coins_bloc/coins_repo.dart
  lib/bloc/trezor_init_bloc/trezor_init_bloc.dart
  lib/model/cex_price.dart
  lib/model/coin.dart
  lib/shared/utils/password.dart
  lib/shared/widgets/coin_balance.dart
  lib/views/wallet/wallet_page/common/asset_list_item.dart
  lib/views/wallet/wallet_page/common/assets_list.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
  lib/views/wallet/wallet_page/wallet_main/active_coins_list.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_manage_section.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_overview.dart
  packages/komodo_ui_kit/lib/src/display/statistic_card.dart
  packages/komodo_ui_kit/pubspec.lock
  pubspec.lock
  pubspec.yaml
Labels: release candidate, QA

#2779 feat: add trading status guard
  assets/translations/en.json
  lib/app_config/app_config.dart
  lib/bloc/app_bloc_root.dart
  lib/bloc/trading_status/trading_status_bloc.dart
  lib/bloc/trading_status/trading_status_event.dart
  lib/bloc/trading_status/trading_status_repository.dart
  lib/bloc/trading_status/trading_status_state.dart
  lib/model/main_menu_value.dart
  lib/router/navigators/page_content/page_content_router_delegate.dart
  lib/router/parsers/root_route_parser.dart
  lib/shared/ui/clock_warning_banner.dart
  lib/shared/widgets/logout_popup.dart
  lib/views/bridge/bridge_page.dart
  lib/views/common/main_menu/main_menu_bar_mobile.dart
  lib/views/common/main_menu/main_menu_desktop.dart
  lib/views/dex/dex_page.dart
  lib/views/main_layout/main_layout.dart
  lib/views/market_maker_bot/market_maker_bot_page.dart
  lib/views/settings/widgets/general_settings/general_settings.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_common_buttons.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
Labels: codex

#2785 chore: sync hot-fix release from `main` to `dev`
  CHANGELOG.md
  assets/translations/en.json
  lib/app_config/app_config.dart
  lib/bloc/app_bloc_root.dart
  lib/bloc/bitrefill/bloc/bitrefill_bloc.dart
  lib/bloc/bitrefill/bloc/bitrefill_event.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_bloc.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_repository.dart
  lib/bloc/cex_market_data/portfolio_growth/portfolio_growth_state.dart
  lib/bloc/cex_market_data/price_chart/models/price_chart_interval.dart
  lib/bloc/cex_market_data/price_chart/models/time_period.dart
  lib/bloc/coins_bloc/coins_repo.dart
  lib/bloc/trading_status/trading_status_bloc.dart
  lib/bloc/trading_status/trading_status_event.dart
  lib/bloc/trading_status/trading_status_repository.dart
  lib/bloc/trading_status/trading_status_state.dart
  lib/bloc/trezor_init_bloc/trezor_init_bloc.dart
  lib/generated/codegen_loader.g.dart
  lib/model/cex_price.dart
  lib/model/coin.dart
  lib/model/main_menu_value.dart
  lib/router/navigators/page_content/page_content_router_delegate.dart
  lib/router/parsers/root_route_parser.dart
  lib/shared/ui/clock_warning_banner.dart
  lib/shared/utils/password.dart
  lib/shared/widgets/coin_balance.dart
  lib/shared/widgets/logout_popup.dart
  lib/views/bitrefill/bitrefill_button.dart
  lib/views/bitrefill/bitrefill_button_view.dart
  lib/views/bitrefill/bitrefill_inappwebview_button.dart
  lib/views/bridge/bridge_confirmation.dart
  lib/views/bridge/bridge_exchange_form.dart
  lib/views/bridge/bridge_page.dart
  lib/views/common/main_menu/main_menu_bar_mobile.dart
  lib/views/common/main_menu/main_menu_bar_mobile_item.dart
  lib/views/common/main_menu/main_menu_desktop.dart
  lib/views/dex/dex_page.dart
  lib/views/dex/simple/confirm/maker_order_confirmation.dart
  lib/views/dex/simple/confirm/taker_order_confirmation.dart
  lib/views/dex/simple/form/maker/maker_form_trade_button.dart
  lib/views/dex/simple/form/taker/taker_form_content.dart
  lib/views/main_layout/main_layout.dart
  lib/views/market_maker_bot/add_market_maker_bot_trade_button.dart
  lib/views/market_maker_bot/market_maker_bot_confirmation_form.dart
  lib/views/market_maker_bot/market_maker_bot_page.dart
  lib/views/settings/widgets/general_settings/general_settings.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_common_buttons.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/wallet_page/common/asset_list_item.dart
  lib/views/wallet/wallet_page/common/assets_list.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
  lib/views/wallet/wallet_page/wallet_main/active_coins_list.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_manage_section.dart
  lib/views/wallet/wallet_page/wallet_main/wallet_overview.dart
  packages/komodo_ui_kit/lib/src/display/statistic_card.dart
  pubspec.yaml
Labels: chore

#2789 fix: disable parent coin removes tokens
  assets/translations/en.json
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_repo.dart
  lib/generated/codegen_loader.g.dart
  lib/shared/utils/utils.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/coins_manager/coins_manager_list_wrapper.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
Labels: codex

#2791 feat: set wallet page as default landing view
  lib/model/main_menu_value.dart
Labels: codex

#2805 fix(copy-address): improve clipboard overlay
  app_theme/lib/src/dark/theme_global_dark.dart
  app_theme/lib/src/light/theme_global_light.dart
  lib/shared/utils/utils.dart
Labels: codex

#2690 feat: add copy address functionality
  app_theme/lib/src/dark/theme_global_dark.dart
  app_theme/lib/src/light/theme_global_light.dart
  assets/translations/en.json
  lib/generated/codegen_loader.g.dart
  lib/services/feedback/feedback_service.dart
  lib/shared/utils/utils.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/coin_details/receive/receive_address_trezor.dart
  lib/views/wallet/coin_details/receive/receive_details.dart
  lib/views/wallet/common/address_copy_button.dart
  lib/views/wallet/wallet_page/wallet_main/active_coins_list.dart
Labels: QA

#2812 fix(withdraw): auto-select source address
  lib/bloc/withdraw_form/withdraw_form_bloc.dart
  lib/views/wallet/coin_details/withdraw_form/withdraw_form.dart
Labels: codex

#2815 fix(wallet): refresh pubkeys after new address
  lib/bloc/coin_addresses/bloc/coin_addresses_bloc.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
Labels: codex

#2795 fix: remove unnecessary provider error logging
  lib/services/feedback/feedback_service.dart
Labels: codex

#2824 fix: import analytics scroll event
  lib/views/wallet/wallet_page/wallet_main/wallet_main.dart
Labels: codex

#2823 test: cover null my_info in swap deserialization
  test_units/main.dart
  test_units/tests/swaps/my_recent_swaps_response_test.dart
Labels: codex

#2816 linux: call XInitThreads() to make X11 access thread-safe
  linux/CMakeLists.txt
  linux/main.cc
Labels: QA

#2831 use segwit variant for default trezor coins
  lib/app_config/app_config.dart
Labels: P1, QA, trezor

#2820 Fix null my_info handling for swaps
  lib/blocs/trading_entities_bloc.dart
  lib/model/swap.dart
  lib/views/dex/dex_helpers.dart
  lib/views/dex/entities_list/history/history_item.dart
  lib/views/dex/entities_list/history/swap_history_sort_mixin.dart
  lib/views/dex/entities_list/in_progress/in_progress_item.dart
  lib/views/dex/entities_list/in_progress/in_progress_list.dart
  lib/views/dex/entity_details/swap/swap_details.dart
  lib/views/dex/entity_details/swap/swap_details_step_list.dart
  test_units/main.dart
  test_units/tests/swaps/my_recent_swaps_response_test.dart
Labels: QA, codex
