Repository KomodoPlatform/komodo-wallet, pull requests merged in 2025-04, with the labels that each got.

#2584 fix(coins-bloc): coins re-activating after being disabled by the user
  lib/bloc/coins_bloc/coins_bloc.dart
Labels: bug, QA

#2533 Add multi-address support to "Faucet" button
  lib/bloc/app_bloc_root.dart
  lib/bloc/faucet_button/faucet_button_bloc.dart
  lib/bloc/faucet_button/faucet_button_event.dart
  lib/bloc/faucet_button/faucet_button_state.dart
  lib/views/wallet/coin_details/coin_details.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_common_buttons.dart
  lib/views/wallet/coin_details/coin_details_info/coin_details_info.dart
  lib/views/wallet/coin_details/coin_page_type.dart
  lib/views/wallet/coin_details/faucet/cubit/faucet_cubit.dart
  lib/views/wallet/coin_details/faucet/cubit/faucet_state.dart
  lib/views/wallet/coin_details/faucet/faucet_button.dart
  lib/views/wallet/coin_details/faucet/faucet_page.dart
  lib/views/wallet/coin_details/faucet/faucet_view.dart
Labels: QA

#2598 fix(custom-token-import): new required parameter in asset constructor
  lib/bloc/custom_token_import/data/custom_token_import_repository.dart
Labels: bug

#2580 feat(auth): SDK password update migration
  assets/translations/en.json
  lib/bloc/auth_bloc/auth_bloc.dart
  lib/bloc/auth_bloc/auth_bloc_state.dart
  lib/bloc/security_settings/security_settings_bloc.dart
  lib/bloc/security_settings/security_settings_state.dart
  lib/generated/codegen_loader.g.dart
  lib/shared/utils/platform_tuner.dart
  lib/views/common/wallet_password_dialog/password_dialog_content.dart
  lib/views/settings/widgets/security_settings/password_update_page.dart
  lib/views/settings/widgets/security_settings/security_settings_main_page.dart
  lib/views/settings/widgets/security_settings/security_settings_page.dart
  lib/views/wallet/wallet_page/common/grouped_asset_ticker_item.dart
  lib/views/wallets_manager/widgets/wallet_import_by_file.dart
  lib/views/wallets_manager/widgets/wallet_login.dart
Labels: QA

#2583 fix(withdraw-form): validation, dropdown icon, and maximum amount field update
  assets/translations/en.json
  lib/bloc/coin_addresses/bloc/coin_addresses_bloc.dart
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_repo.dart
  lib/bloc/withdraw_form/withdraw_form_bloc.dart
  lib/bloc/withdraw_form/withdraw_form_state.dart
  lib/generated/codegen_loader.g.dart
  lib/views/wallet/coin_details/coin_details_info/coin_addresses.dart
  lib/views/wallet/coin_details/withdraw_form/withdraw_form.dart
  lib/views/wallet/common/wallet_helper.dart
Labels: bug, QA

#2587 Chore/localise hardcoded strings
  assets/translations/en.json
  lib/generated/codegen_loader.g.dart
  lib/views/bitrefill/bitrefill_inappwebview_button.dart
  lib/views/main_layout/main_layout.dart
  lib/views/wallet/coin_details/withdraw_form/widgets/fill_form/fields/fields.dart
  lib/views/wallet/coin_details/withdraw_form/withdraw_form.dart
  lib/views/wallet/wallet_page/charts/coin_prices_chart.dart
  lib/views/wallet/wallet_page/common/coins_list_header.dart
  lib/views/wallet/wallet_page/common/expandable_coin_list_item.dart
  lib/views/wallet/wallet_page/wallet_main/active_coins_list.dart
Labels: QA

#2577 Aligned Column Headers
  assets/translations/en.json
  lib/generated/codegen_loader.g.dart
  lib/views/wallet/wallet_page/common/coins_list_header.dart
Labels: QA

#2566 fix(nft): add nft v2 and hd wallet support
  app_theme/lib/src/new_theme/extensions/text_theme_extension.dart
  assets/translations/en.json
  lib/app_config/app_config.dart
  lib/bloc/app_bloc_root.dart
  lib/bloc/coins_bloc/coins_bloc.dart
  lib/bloc/coins_bloc/coins_state.dart
  lib/bloc/nft_receive/bloc/nft_receive_bloc.dart
  lib/bloc/nft_receive/bloc/nft_receive_event.dart
  lib/bloc/nft_receive/bloc/nft_receive_state.dart
  lib/bloc/nft_transactions/nft_txn_repository.dart
  lib/bloc/nft_withdraw/nft_withdraw_bloc.dart
  lib/bloc/nft_withdraw/nft_withdraw_repo.dart
  lib/bloc/nfts/nft_main_bloc.dart
  lib/bloc/nfts/nft_main_event.dart
  lib/bloc/nfts/nft_main_repo.dart
  lib/bloc/nfts/nft_main_state.dart
  lib/bloc/trezor_bloc/trezor_repo.dart
  lib/blocs/trezor_coins_bloc.dart
  lib/generated/codegen_loader.g.dart
  lib/main.dart
  lib/mm2/mm2.dart
  lib/mm2/mm2_api/mm2_api.dart
  lib/mm2/mm2_api/mm2_api_nft.dart
  lib/mm2/mm2_api/rpc/base.dart
  lib/mm2/mm2_api/rpc/nft/refresh_nft_metadata/refresh_nft_metadata_req.dart
  lib/mm2/mm2_api/rpc/nft/update_nft/update_nft_req.dart
  lib/mm2/mm2_api/rpc/nft/withdraw/withdraw_nft_request.dart
  lib/mm2/mm2_api/rpc/withdraw/withdraw_errors.dart
  lib/model/hd_account/hd_account.dart
  lib/model/nft.dart
  lib/shared/widgets/copyable_address_dialog.dart
  lib/views/nfts/common/widgets/nft_failure.dart
  lib/views/nfts/common/widgets/nft_image.dart
  lib/views/nfts/nft_list/nft_list.dart
  lib/views/nfts/nft_main/nft_main_controls.dart
  lib/views/nfts/nft_main/nft_main_failure.dart
  lib/views/nfts/nft_main/nft_refresh_button.dart
  lib/views/nfts/nft_page.dart
  lib/views/nfts/nft_receive/common/nft_failure_page.dart
  lib/views/nfts/nft_receive/common/nft_receive_card.dart
  lib/views/nfts/nft_receive/desktop/nft_receive_desktop_view.dart
  lib/views/nfts/nft_receive/mobile/nft_receive_mobile_view.dart
  lib/views/nfts/nft_receive/nft_receive_page.dart
  lib/views/nfts/nft_receive/nft_receive_view.dart
  lib/views/nfts/nft_tabs/nft_tab.dart
  lib/views/nfts/nft_tabs/nft_tabs.dart
  lib/views/nfts/nft_transactions/common/pages/nft_txn_failure_page.dart
  lib/views/nfts/nft_transactions/desktop/nft_txn_desktop_page.dart.dart
  lib/views/nfts/nft_transactions/desktop/widgets/nft_txn_desktop_card.dart
  lib/views/nfts/nft_transactions/desktop/widgets/nft_txn_desktop_header.dart
  lib/views/nfts/nft_transactions/mobile/widgets/nft_txn_copied_text.dart
  lib/views/nfts/nft_transactions/mobile/widgets/nft_txn_mobile_card.dart
  lib/views/wallet/coin_details/coin_details.dart
  lib/views/wallet/coin_details/coin_details_info/charts/animated_portfolio_charts.dart
  lib/views/wallet/coin_details/receive/receive_address.dart
  lib/views/wallet/coin_details/receive/receive_address_trezor.dart
  lib/views/wallet/coin_details/receive/receive_details.dart
  lib/views/wallet/coin_details/receive/request_address_button.dart
  lib/views/wallets_manager/widgets/wallet_creation.dart
Labels: bug, P0, QA
